#!/bin/sh

set -eu

aws s3 sync \
  --acl public-read \
  --region eu-west-1 \
  --cache-control 'public, max-age=31536000' \
  _site/assets/ s3://2014.okfestival.org/assets/ \
  "$@"

aws s3 sync \
  --acl public-read \
  --region eu-west-1 \
  --cache-control 'public, max-age=600' \
  --include "index.html,okfestival2014.ics" \
  _site/ s3://2014.okfestival.org/ \
  "$@"
